### ISSUE TITLE
s3 store

### ISSUE THREAD

**Issue by luisgallon** [cerbos/cerbos-aws-lambda#5]
Hello,

I have been trying to follow all your steps in order to run this in a lambda but it has been impossible.

I am using s3 as disk as part of the config file:
`cerbos-aws-lambda\conf.default.yml`

```
storage:
  driver: "blob"
  blob:
    # This section is required only if storage.driver is blob.
    bucket: "s3://cerbos-test-pdp?region=us-west-2" 
    downloadTimeout: 30s # DownloadTimeout specifies the timeout for downloading from cloud storage.
    prefix: policies # Prefix specifies a subdirectory to download.
    requestTimeout: 10s # RequestTimeout specifies the timeout for an HTTP request.
    updatePollInterval: 15s # UpdatePollInterval specifies the interval to poll the cloud storage. Set to 0 to disable.
```

And just in case, I added the s3 config as part of the sam.yaml file:
```
Variables:
          BUCKET_URL: "s3://cerbos-test-pdp?region=us-west-2"
          BUCKET_PREFIX: "policies"
          CERBOS_LOG_LEVEL: DEBUG
```

and the set of permissions I attached to the lambda running the cerbos image:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:*",
                "s3-object-lambda:*"
            ],
            "Resource": "arn:aws:s3:::cerbos-test-pdp/*"
        }
    ]
}
```

`ERROR: failed to create store: unknown storage driver [blob]`

Please, any help is appreciated. This is driving me nuts.

thanks.
